### PR TITLE
Added test for Route1

### PR DESCRIPTION
**Pull request by holgero**
Not sure if it is the right way to pass the endpoints a route should refer to as Strings in one of its constructors, but it seems to work just fine (at least in the test case). 

What do you think about this?

### CODE REVIEW

**Comment by dasniko** [comment]
Good approach, and it works anyway.
But as we are using spring framework, we should inject the source/target values from a properties-file or similar. In the tests we can use an extra properties file or just overwrite the values before injection. However, constructor-"injection" isn't a good approach at all... ;-)

**Comment by holgero** [comment]
Better this way? Last commit sets the target and source in the camel-context.xml for production and overwrites them in the test (by calling the setters explicitely).

**Comment by dasniko** [comment]
Redundant declaration of the (Route)Bean is not the right way!

My preferred solution:
Loading a properties file with the endpoint information in the spring context with `PropertyPlaceholderConfigurer` and inject the appropriate variables in the RouteBean (with `@Value` at your private members).
For the tests, easily use another properties file (preferred) or overwriting the properties in your test classes.

I will do this in the next days or weeks... just gimme some time.

**Comment by holgero** [comment]
I tried, but didn't succeed completely with the property stuff. It worked locally for the productive case, but I failed with overwriting it in the tests. So if you don't have a better solution neither, why not use the version with the constructor injection?

IMHO (as a TDD advocate) having tests is much more important than following any other paradigm...

**Pull request closed without merging**
